name: build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up the Java JDK
      uses: actions/setup-java@v2.4.0
      with:
        java-version: '15'
        distribution: 'adopt'

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.0.1
      with:
        arguments: build

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run Tests
      run: ./gradlew test

    - name: Run Test Coverage
      run: ./gradlew jacocoTestReport

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: test-results/**/*.xml


